### PR TITLE
Fix error C4800, Implicit conversion from 'UActorComponent *' to bool.

### PR DESCRIPTION
**Pull request by monizka**
To avoid possible information loss, use 'IsValid' for ActorComponent pointer's validity.

### CODE REVIEW

**Review by HiIAmMoot — CHANGES_REQUESTED** [review]
Do you think you could get rid of the if statement entirely? Something like `IsValid(Actor) && IsValid(Actor->...)?`

**Comment by monizka** [comment]
> Do you think you could get rid of the if statement entirely? Something like `IsValid(Actor) && IsValid(Actor->...)?`
> 
> Further more, is this the only line of code where the error occurs? Or should this be changed on more IsValid nodes?

That was the only line caused the error. I haven't read all codes yet, but just fixing compile error.
So I am not sure if it needs more modification, but I will let you know if I find on future.

And yes, I think we can get rid of if statement as you said.

**Comment by HiIAmMoot** [comment]
> > Do you think you could get rid of the if statement entirely? Something like `IsValid(Actor) && IsValid(Actor->...)?`
> > Further more, is this the only line of code where the error occurs? Or should this be changed on more IsValid nodes?
> 
> That was the only line caused the error. I haven't read all codes yet, but just fixing compile error.
> So I am not sure if it needs more modification, but I will let you know if I find on future.
> 
> And yes, I think we can get rid of if statement as you said.

Great! I will merge once that if statement is removed

**Comment by monizka** [comment]
> 
> Great! I will merge once that if statement is removed

Done!

**Pull request merged**
